name: Publish release

env:
  REGISTRY: harbor.goopy.us
  IMAGE: sackbuoy/kraken-grid
  USERNAME: robot$gh-action

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    # Ensure Nix and Docker are set up
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ REGISTRY }}
        username: ${{ USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Build Docker image with Nix
      run: |
        nix build --system x86_64-linux
        docker load < result

    - name: Name Docker image
      run: |
        docker tag $(docker images -q | head -n 1) ${REGISTRY}/${IMAGE}:latest
        docker tag ${REGISTRY}/${IMAGE}:latest ${REGISTRY}/${IMAGE}:${{ github.ref_name }}

    - name: Push Docker image
      run: |
        docker push -a ${REGISTRY}/${IMAGE}



